safe: 
  - alabaster
  - Babel
  - beautifulsoup4
  - certifi
  - charset-normalizer
  - docutils
  - furo
  - idna
  - imagesize
  - Jinja2
  - markdown-it-py
  - MarkupSafe
  - mdit-py-plugins
  - mdurl
  - packaging
  - Pygments
  - pyparsing
  - pytz
  - PyYAML
  - requests
  - snowballstemmer
  - soupsieve
  - sphinx-basic-ng
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - typing_extensions
  - urllib3
