image: gitpod/workspace-python:latest

tasks:
  - init: |
      python3 -m venv .venv
      source .venv/bin/activate
      python3 -m pip install -r requirements.txt

vscode:
  extensions:
    - ms-python.python
    - yzhang.markdown-all-in-one
